import type { CurriculumModule, Lesson, McqLessonQuestion } from "../curriculumTypes";
import { phasedMcqQuestions } from "../legacyMcq";

/** Module 2 — Contact vs Non-contact Forces (Motion & Forces pathway). */
export const physicsMotion02Module: CurriculumModule = {
  moduleId: "physics_motion_02",
  title: "Contact vs Non-contact Forces",
  pathway: "Motion & Forces",
  tier: "beginner",
  environment: {
    theme: "force_interactions",
    primaryColors: ["cyan", "purple"],
    backgroundStyle: "neon_physics_lab",
    particleStyle: "interaction_pulses",
  },
  visualMotifs: [
    "bowling-ball",
    "magnet-arcs",
    "gravity-pull",
    "push-force-arrows",
    "contact-ripple",
    "field-lines",
  ],
  lessonId: "lesson-2-contact-noncontact",
};

const contactVisual = (
  focusObject: string,
  highlightEffect: string,
  motionOverlay: string,
  motifs: string[]
): McqLessonQuestion["visualBehavior"] => ({
  focusObject,
  highlightEffect,
  motionOverlay,
  motifs,
});

const rawQuestions: Omit<McqLessonQuestion, "phase" | "questionType">[] = [
  {
    id: "contact-q01",
    prompt: "What type of force occurs when two objects physically touch?",
    options: ["Gravity", "Magnetic force", "Contact force", "Electric force at a distance"],
    correctIndex: 2,
    explanation: "Contact forces require physical interaction between surfaces or bodies.",
    difficulty: 1,
    conceptTags: ["contact_force", "interaction"],
    visualBehavior: contactVisual(
      "bowling_ball_collision",
      "impact_pulse",
      "collision_lines",
      ["bowling-ball-collision", "contact-ripple", "push-force-arrows"]
    ),
    reinforcement: { flashcardEligible: true, confusionTriggers: ["gravity", "magnetic"] },
  },
  {
    id: "contact-q02",
    prompt: "Pushing a book across a desk is an example of:",
    options: ["Non-contact force", "Contact force", "Gravitational field", "Magnetic induction"],
    correctIndex: 1,
    explanation: "Your hand must touch the book to push it — a classic contact interaction.",
    difficulty: 1,
    conceptTags: ["contact_force", "push"],
    visualBehavior: contactVisual("push_surface", "slow_pulse", "force_arrows", [
      "push-force-arrows",
      "contact-ripple",
      "field-lines",
    ]),
    reinforcement: { flashcardEligible: true, confusionTriggers: ["non-contact", "gravitational"] },
  },
  {
    id: "contact-q03",
    prompt: "Friction between your shoes and the ground is:",
    options: ["A non-contact force", "A contact force", "Only visible in space", "A type of light"],
    correctIndex: 1,
    explanation: "Friction acts where surfaces touch — it is always a contact force.",
    difficulty: 1,
    conceptTags: ["friction", "contact_force"],
    visualBehavior: contactVisual("shoe_ground", "friction_glow", "surface_ripple", [
      "contact-ripple",
      "push-force-arrows",
      "bowling-ball-collision",
    ]),
    reinforcement: { flashcardEligible: true, confusionTriggers: ["non-contact"] },
  },
  {
    id: "contact-q04",
    prompt: "The upward force a table exerts on a resting book is called:",
    options: ["Gravity", "Normal force", "Magnetism", "Tidal force"],
    correctIndex: 1,
    explanation: "The normal force is a contact force — the table pushes back where it touches the book.",
    difficulty: 2,
    conceptTags: ["normal_force", "contact_force"],
    visualBehavior: contactVisual("table_support", "support_glow", "vertical_arrows", [
      "contact-ripple",
      "gravity-pull",
      "field-lines",
    ]),
    reinforcement: { flashcardEligible: true, confusionTriggers: ["gravity"] },
  },
  {
    id: "contact-q05",
    prompt: "Gravity pulling an apple toward Earth is best classified as:",
    options: ["Contact force", "Non-contact force", "Friction", "Tension"],
    correctIndex: 1,
    explanation: "Gravity acts at a distance through a field — no touching is required.",
    difficulty: 1,
    conceptTags: ["gravity", "non_contact_force"],
    visualBehavior: contactVisual("apple_earth", "gravity_stream", "field_pull", [
      "gravity-pull",
      "gravity-field",
      "field-lines",
    ]),
    reinforcement: { flashcardEligible: true, confusionTriggers: ["contact", "friction"] },
  },
  {
    id: "contact-q06",
    prompt: "A magnet attracting a paper clip without touching it demonstrates:",
    options: ["Contact force", "Non-contact force", "Normal force", "Air resistance only"],
    correctIndex: 1,
    explanation: "Magnetic forces can act across gaps — they are non-contact forces.",
    difficulty: 1,
    conceptTags: ["magnetism", "non_contact_force"],
    visualBehavior: contactVisual("magnet_clip", "arc_pulse", "field_arcs", [
      "magnet-arcs",
      "metal-float",
      "field-lines",
    ]),
    reinforcement: { flashcardEligible: true, confusionTriggers: ["contact", "normal"] },
  },
  {
    id: "contact-q07",
    prompt: "Which force does NOT require objects to touch?",
    options: ["Friction", "Normal force", "Magnetism", "Tension in a pulled rope"],
    correctIndex: 2,
    explanation: "Magnetism works through a field at a distance. The others need contact or a connecting rope.",
    difficulty: 2,
    conceptTags: ["non_contact_force", "magnetism"],
    visualBehavior: contactVisual("floating_metals", "arc_pulse", "field_arcs", [
      "magnet-arcs",
      "metal-float",
      "gravity-field",
    ]),
    reinforcement: { flashcardEligible: true, confusionTriggers: ["friction", "tension"] },
  },
  {
    id: "contact-q08",
    prompt: "Opening a door by pushing the handle involves:",
    options: ["Only gravity", "A contact force", "Only magnetism", "No force at all"],
    correctIndex: 1,
    explanation: "Your hand contacts the handle — the push is a contact force that rotates the door.",
    difficulty: 1,
    conceptTags: ["contact_force", "push"],
    visualBehavior: contactVisual("door_push", "impact_pulse", "collision_lines", [
      "push-force-arrows",
      "contact-ripple",
      "bowling-ball-collision",
    ]),
    reinforcement: { flashcardEligible: true, confusionTriggers: ["gravity", "magnetism"] },
  },
  {
    id: "contact-q09",
    prompt: "Earth's pull on the Moon happens because of:",
    options: ["Friction between them", "Gravitational non-contact force", "Direct contact", "Air pressure"],
    correctIndex: 1,
    explanation: "The Moon never touches Earth, yet gravity binds them — a field-based non-contact force.",
    difficulty: 2,
    conceptTags: ["gravity", "non_contact_force", "field"],
    visualBehavior: contactVisual("earth_moon", "gravity_stream", "orbital_pull", [
      "gravity-pull",
      "gravity-field",
      "field-lines",
    ]),
    reinforcement: { flashcardEligible: true, confusionTriggers: ["friction", "contact"] },
  },
  {
    id: "contact-q10",
    prompt: "Rubbing your hands together warms them mainly due to:",
    options: ["Magnetic fields", "Friction (contact force)", "Gravity alone", "Electric charge at a distance"],
    correctIndex: 1,
    explanation: "Skin surfaces slide against each other — friction is a contact force that transfers energy as heat.",
    difficulty: 2,
    conceptTags: ["friction", "contact_force"],
    visualBehavior: contactVisual("hands_rub", "friction_glow", "surface_ripple", [
      "contact-ripple",
      "push-force-arrows",
      "bowling-ball-collision",
    ]),
    reinforcement: { flashcardEligible: true, confusionTriggers: ["magnetic", "gravity"] },
  },
  {
    id: "contact-q11",
    prompt: "Static electricity making hair stand up after combing is:",
    options: ["Only a contact force", "A non-contact electric force", "The same as friction only", "Not a force"],
    correctIndex: 1,
    explanation: "Charged objects can attract hair at a short distance — an electric field effect, non-contact.",
    difficulty: 3,
    conceptTags: ["electrostatic", "non_contact_force"],
    visualBehavior: contactVisual("charged_hair", "field_shimmer", "electric_arcs", [
      "field-lines",
      "metal-float",
      "magnet-arcs",
    ]),
    reinforcement: { flashcardEligible: true, confusionTriggers: ["contact only", "friction only"] },
  },
  {
    id: "contact-q12",
    prompt: "A climber hanging from a rope feels tension. Tension is:",
    options: ["Non-contact because ropes are long", "A contact force transmitted through the rope", "Gravity renamed", "Magnetism in disguise"],
    correctIndex: 1,
    explanation: "The rope pulls on the climber where they connect — force travels through contact in the material.",
    difficulty: 3,
    conceptTags: ["tension", "contact_force"],
    visualBehavior: contactVisual("rope_tension", "tension_glow", "vertical_arrows", [
      "push-force-arrows",
      "contact-ripple",
      "gravity-pull",
    ]),
    reinforcement: { flashcardEligible: true, confusionTriggers: ["non-contact", "gravity renamed"] },
  },
  {
    id: "contact-q13",
    prompt: "Air resistance on a falling feather is:",
    options: ["Non-contact — no touch needed", "A contact force from air molecules hitting the feather", "Gravity", "Magnetism"],
    correctIndex: 1,
    explanation: "Air pushes the feather through countless tiny collisions — still a contact interaction at micro-scale.",
    difficulty: 3,
    conceptTags: ["air_resistance", "contact_force"],
    visualBehavior: contactVisual("feather_fall", "drag_streaks", "collision_lines", [
      "contact-ripple",
      "field-lines",
      "push-force-arrows",
    ]),
    reinforcement: { flashcardEligible: true, confusionTriggers: ["non-contact", "gravity", "magnetism"] },
  },
  {
    id: "contact-q14",
    prompt: "Two bowling balls colliding on a lane exchange momentum through:",
    options: ["Gravity only", "Contact force at impact", "Magnetic repulsion only", "No interaction"],
    correctIndex: 1,
    explanation: "At impact, surfaces press together — a sharp contact force changes their motion.",
    difficulty: 1,
    conceptTags: ["collision", "contact_force"],
    visualBehavior: contactVisual(
      "bowling_ball_collision",
      "impact_pulse",
      "collision_shockwave",
      ["bowling-ball-collision", "contact-ripple", "push-force-arrows"]
    ),
    reinforcement: { flashcardEligible: true, confusionTriggers: ["gravity only", "magnetic"] },
  },
  {
    id: "contact-q15",
    prompt: "Which pair is BOTH non-contact forces?",
    options: ["Friction and normal force", "Gravity and magnetism", "Push and pull by hand", "Tension and friction"],
    correctIndex: 1,
    explanation: "Gravity and magnetism both act at a distance without requiring direct touch.",
    difficulty: 2,
    conceptTags: ["non_contact_force", "classification"],
    visualBehavior: contactVisual("dual_fields", "field_shimmer", "split_scene", [
      "gravity-pull",
      "magnet-arcs",
      "field-lines",
    ]),
    reinforcement: { flashcardEligible: true, confusionTriggers: ["friction", "push"] },
  },
  {
    id: "contact-q16",
    prompt: "The key difference between contact and non-contact forces is:",
    options: [
      "Contact forces need physical interaction; non-contact act through fields at a distance",
      "Contact forces are weaker always",
      "Non-contact forces only exist in space",
      "There is no real difference",
    ],
    correctIndex: 0,
    explanation: "Touch vs field — that is the organizing idea for every example in this module.",
    difficulty: 2,
    conceptTags: ["classification", "field"],
    visualBehavior: contactVisual("split_chamber", "slow_pulse", "split_scene", [
      "bowling-ball-collision",
      "magnet-arcs",
      "gravity-pull",
      "field-lines",
    ]),
    reinforcement: { flashcardEligible: true, confusionTriggers: ["weaker", "no difference"] },
  },
  {
    id: "contact-q17",
    prompt: "A boat floating in water is pushed upward by buoyancy. Buoyancy is:",
    options: [
      "Non-contact because water is invisible",
      "A contact force from water molecules pushing the hull",
      "Magnetism from Earth",
      "Not a force",
    ],
    correctIndex: 1,
    explanation: "Water presses on the hull where they meet — buoyancy spreads many small contact pushes over area.",
    difficulty: 3,
    conceptTags: ["buoyancy", "contact_force"],
    visualBehavior: contactVisual("hull_water", "support_glow", "surface_ripple", [
      "contact-ripple",
      "gravity-pull",
      "field-lines",
    ]),
    reinforcement: { flashcardEligible: true, confusionTriggers: ["non-contact", "magnetism"] },
  },
  {
    id: "contact-q18",
    prompt: "A satellite orbiting Earth experiences primarily:",
    options: [
      "Friction from air in empty space",
      "Non-contact gravitational force",
      "Contact force from the atmosphere touching it",
      "Magnetic friction from the poles only",
    ],
    correctIndex: 1,
    explanation: "In orbit, gravity curves the path at a distance — the signature non-contact force for celestial motion.",
    difficulty: 2,
    conceptTags: ["gravity", "non_contact_force", "orbit"],
    visualBehavior: contactVisual("satellite_orbit", "gravity_stream", "orbital_pull", [
      "gravity-pull",
      "gravity-field",
      "field-lines",
    ]),
    reinforcement: { flashcardEligible: true, confusionTriggers: ["friction", "contact atmosphere"] },
  },
];

export const contactForcesLesson: Lesson = {
  id: physicsMotion02Module.lessonId,
  title: "Lesson 2: Contact vs Non-Contact Forces",
  explanation:
    "Forces are either contact forces (push, pull, friction, normal, tension, buoyancy) or non-contact forces (gravity, magnetism, electrostatic). Contact means surfaces or connected materials must interact. Non-contact means invisible fields bridge the gap — gravity pulls downward, magnets tug across air, and charged objects attract without touching.",
  visualKeywords: ["bowling collision", "gravity field", "magnetism", "friction", "door push"],
  conceptTags: ["contact force", "non-contact force", "field", "friction", "gravity", "magnetism"],
  visualTheme: {
    backgroundScene: "contact_fields",
    accentColors: ["cyan", "purple"],
    motifs: ["bowling-ball", ...physicsMotion02Module.visualMotifs.filter((m) => m !== "bowling-ball")],
  },
  visualScene: {
    focusObject: "bowling_ball",
    motionType: "collision",
    effectOverlay: "force_arrows",
    animationStyle: "slow_pulse",
  },
  reinforcementFeedback: {
    correct: "Nice. You separated touch-based interactions from distance-based field forces.",
    incorrect: "Rule of thumb: if objects must touch (or connect through a rope/surface), think contact. If it works across a gap, think field.",
  },
  questions: phasedMcqQuestions(rawQuestions),
};
